### ISSUE TITLE
服务器有故障吗？

### ISSUE THREAD

**Issue by BobCN2017** [dueros/dcs-sdk-java#31]
这两天突然无法连接，测试了一下例子App，也显示登陆成功，但识别失败。log中显示：
 okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL 这是什么原因呢？

11-03 09:20:28.799 3741-12501/com.baidu.duer.dcs D/DCS-HttpLog: request: POST [https://dueros-h2.baidu.com/dcs/v1/events] null
                                                                Content-Type: multipart/form-data boundary=dumi-boundory
                                                                dueros-device-id: ffffffff-e77c-2c93-0000-000054369570
                                                                debug: 0
                                                                Authorization: Bearer 23.1736c34e78d47b79d3cb54f025d133f9.2592000.1512213147.3222254029-10103632
11-03 09:20:28.846 3741-14629/com.baidu.duer.dcs D/wakeup: WakeUpDecode ret=-1
11-03 09:20:28.846 3741-14629/com.baidu.duer.dcs D/wakeup: WakeUpDecode senArr=
11-03 09:20:28.846 3741-14629/com.baidu.duer.dcs D/wakeup: WakeUpDecode wakeWord_frame_len_invoke=-1
11-03 09:20:28.846 3741-14629/com.baidu.duer.dcs D/wakeup: WakeUpDecode is_confidence_invoke=1
11-03 09:20:28.847 3741-14629/com.baidu.duer.dcs D/wakeup: WakeUpDecode voice_offset_invoke=175
11-03 09:20:28.847 3741-14629/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup after wakeUpDecode over !!
11-03 09:20:28.872 3741-14629/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup after linkedBlockingDeque size:0
11-03 09:20:42.560 3741-3741/com.baidu.duer.dcs D/DCS-DcsClient: onError,
                                                                 okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
                                                                     at okhttp3.internal.http2.Http2Stream.checkOutNotClosed(Http2Stream.java:567)
                                                                     at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:501)
                                                                     at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:481)
                                                                     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
                                                                     at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
                                                                     at com.baidu.duer.dcs.framework.message.DcsStreamRequestBody.writeTo(DcsStreamRequestBody.java:48)
                                                                     at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
                                                                     at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
                                                                     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at com.baidu.duer.dcs.http.intercepter.LoggingInterceptor.intercept(LoggingInterceptor.java:42)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
11-03 09:20:42.566 3741-3741/com.baidu.duer.dcs D/DCS-VoiceInputDeviceModule: onFailed,errorMessage:stream was reset: CANCEL
11-03 09:20:42.571 3741-3741/com.baidu.duer.dcs D/DCS-DcsDemoActivity: onFailed-errorMessage:stream was reset: CANCEL
11-03 09:20:42.579 3741-16029/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup wakeUpDecode start
11-03 09:20:42.582 3741-3741/com.baidu.duer.dcs D/DCS-BaseMultiChannelMediaPlayer: ChannelMediaPlayer-setActive-isActive:false
11-03 09:20:42.582 3741-15180/com.baidu.duer.dcs D/DCS-AudioVoiceInputThread: closed
11-03 09:20:42.589 3741-12461/com.baidu.duer.dcs D/DCS-OkHttpRequestImpl: doGetPingAsync
11-03 09:20:42.594 3741-15180/com.baidu.duer.dcs D/DCS-AudioVoiceInputThread: onWriteFinished 
11-03 09:20:42.598 3741-12501/com.baidu.duer.dcs D/DCS-HttpLog: request: GET [https://dueros-h2.baidu.com/dcs/v1/ping] null
                                                                Content-Type: multipart/form-data boundary=dumi-boundory
                                                                dueros-device-id: ffffffff-e77c-2c93-0000-000054369570
                                                                debug: 0
                                                                Authorization: Bearer 23.1736c34e78d47b79d3cb54f025d133f9.2592000.1512213147.3222254029-10103632

**Comment by BobCN2017** [comment]
11.7日测试发现已恢复正常。
