### ISSUE TITLE
DCS Android4.4 报以下错误再次唤醒对话无效 

### ISSUE THREAD

**Issue by xiaoxinxing12** [dueros/dcs-sdk-java#48]
DCS Android4.4 报以下错误再次唤醒对话无效 
比如在播一首歌 ，再次唤醒对话无效了

01-18 10:05:55.594 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:55.664 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:55.704 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:55.774 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:55.844 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:55.914 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:55.964 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:56.034 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:56.104 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:56.174 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:56.214 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:56.294 1887-9909/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:05:56.324 1887-9909/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup wakeUpDecode ret:1
01-18 10:05:56.324 1887-9909/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup wakeUpDecode succeed !!
01-18 10:05:56.324 1887-9909/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup after wakeUpDecode over !!
01-18 10:05:56.334 1887-9909/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup after linkedBlockingDeque size:0
01-18 10:05:56.334 1887-1887/com.baidu.duer.dcs D/DCS-BaseMultiChannelMediaPlayer: ChannelMediaPlayer-setActive-isActive:true
01-18 10:05:56.334 1887-1887/com.baidu.duer.dcs D/DCS-BaseMultiChannelMediaPlayer: ChannelMediaPlayer-stop-channelName:dialog
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/AudioTrackPlayerImpl: currentFrame=0
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/AudioTrackPlayerImpl: playTime=0.0
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/AudioTrackPlayerImpl: stop-PlayState:2
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/AudioTrackPlayerImpl: stop-ok
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/DCS-BaseMultiChannelMediaPlayer: ListenerProxy onStopped  del:dialog
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/DCS-BaseMultiChannelMediaPlayer: ListenerProxy onStopped after del :0
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/MediaPlayerImpl: mCurrentState = STOPPED
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs D/MediaPlayerImpl: mCurrentState = IDLE
01-18 10:05:56.344 1887-1887/com.baidu.duer.dcs E/logId: logId send  stream start
01-18 10:05:56.354 1887-1887/com.baidu.duer.dcs D/time: 开始发语音
01-18 10:05:56.354 1887-1887/com.baidu.duer.dcs D/time: logid：de7f9317-32f8-4602-8575-938d4cb3bb2d
01-18 10:05:56.354 1887-1887/com.baidu.duer.dcs D/DCS-DcsDemoActivity: onStartRecord
01-18 10:05:56.394 1887-1887/com.baidu.duer.dcs D/dalvikvm: GC_FOR_ALLOC freed 602K, 18% free 4517K/5488K, paused 24ms, total 24ms
01-18 10:06:18.044 1887-1887/com.baidu.duer.dcs D/DCS-DcsClient: onError,
                                                                 javax.net.ssl.SSLException: Write error: ssl=0x73c7fec0: I/O error during system call, Connection reset by peer
                                                                     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
                                                                     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:731)
                                                                     at okio.Okio$1.write(Okio.java:79)
                                                                     at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
                                                                     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
                                                                     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
                                                                     at com.baidu.dcs.okhttp3.internal.http1.Http1Codec$ChunkedSink.write(Http1Codec.java:327)
                                                                     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
                                                                     at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
                                                                     at com.baidu.duer.dcs.framework.message.DcsStreamRequestBody.writeTo(DcsStreamRequestBody.java:48)
                                                                     at com.baidu.dcs.okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
                                                                     at com.baidu.dcs.okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
                                                                     at com.baidu.dcs.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:69)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:134)
                                                                     at com.baidu.dcs.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:134)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
                                                                     at com.baidu.dcs.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:95)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:134)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
                                                                     at com.baidu.dcs.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:134)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:134)
                                                                     at com.baidu.dcs.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
                                                                     at com.baidu.dcs.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:206)
                                                                     at com.baidu.dcs.okhttp3.RealCall$AsyncCall.execute(RealCall.java:145)
                                                                     at com.baidu.dcs.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:841)
01-18 10:06:18.044 1887-1887/com.baidu.duer.dcs D/DCS-VoiceInputDeviceModule: onFailed,errorMessage:Write error: ssl=0x73c7fec0: I/O error during system call, Connection reset by peer
01-18 10:06:18.054 1887-1887/com.baidu.duer.dcs D/DCS-DcsDemoActivity: onFailed-errorMessage:Write error: ssl=0x73c7fec0: I/O error during system call, Connection reset by peer
01-18 10:06:18.054 1887-10062/com.baidu.duer.dcs I/DCS-WakeUpDecodeThread: wakeup wakeUpDecode start
01-18 10:06:18.054 1887-1887/com.baidu.duer.dcs D/DCS-DcsDemoActivity: onFinishRecord
01-18 10:06:18.054 1887-9943/com.baidu.duer.dcs D/DCS-AudioVoiceInputThread: closed
01-18 10:06:18.054 1887-1887/com.baidu.duer.dcs D/DCS-WakeUpImpl: wakeup wakeUpDecodeThread  is Started !
01-18 10:06:18.054 1887-9943/com.baidu.duer.dcs D/DCS-AudioVoiceInputThread: onWriteFinished 
01-18 10:06:18.054 1887-1887/com.baidu.duer.dcs D/DCS-BaseMultiChannelMediaPlayer: ChannelMediaPlayer-setActive-isActive:false
01-18 10:06:18.064 1887-1887/com.baidu.duer.dcs D/DCS-DcsDemoActivity: onFinishRecord
01-18 10:06:18.064 1887-1887/com.baidu.duer.dcs D/DCS-WakeUpImpl: wakeup wakeUpDecodeThread  is Started !
01-18 10:06:18.114 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.184 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.234 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.304 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.374 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.444 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.504 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.554 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.624 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.694 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.764 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.814 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.884 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:18.954 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024
01-18 10:06:19.024 1887-10062/com.baidu.duer.dcs D/wakeup: WakeUpDecode data_ GetArrayLength=1024

**Comment by xjgpeople** [comment]
我也遇到了这个问题,不知道有没有解决.

**Comment by jinyingfeng** [comment]
我也遇到此问题，请问有没有人来回答一下，如何解决，长时间播放完一首歌曲，然后就这样了，5.1不会有问题，4.4会有问题
