### ISSUE TITLE
索尼L39t 4.2.2 初始化时抱错，无法使用

### ISSUE THREAD

**Issue by code4a** [dueros/dcs-sdk-java#52]
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libbdEASRAndroid.so" needed by "libwakeup.so"; caused by load_library(linker.cpp:745): library "libbdEASRAndroid.so" not found
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:535)

**Comment by code4a** [comment]
// 加载动态库.so文件
    static {
        // 唤醒词解码so库
        System.loadLibrary("bdEASRAndroid");
        System.loadLibrary("wakeup");
    }

变更两个so的加载顺序
