### ISSUE TITLE
缺少so文件

### ISSUE THREAD

**Issue by 258459885596** [dueros/dcs-sdk-java#60]
以下错误
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[zip fle "/data/app/com.baidu.duer.dcs-4FsOslyGw3NtfNrXGZdL-A==/base.apk"],nativeLibraryDirectories=[data/app/com.baidu.duer.dcs-4FsOslyGw3NtfNrXGZdL-A==/ib/arm, /system/fake-libs, /data/app/com.baidu.duer.dcs-4FsOslyGw3NtfNrXGZdL-A==/base.apk!/ib/armeabi, /system/ib,/system/vendor/ib]] couldn't find "libwakeup.so"
atjava.lang.Runtime.loadLibrary0(Runtime.java:1011)
at java.lang.System.loadLibrary(System.java:1657)
at
com.baidu.duer.dcs.androidsystemimpl.wakeup.WakeUpNative.<clinit>(WakeUpNative.java:28)
at com.baidu.duer.dcs.androidsystemimpl.wakeup.WakeUplmpl.<init>(WakeUplmpljava:60)com.baidu.duer.dcs.androidsystemimpl.PlatformFactorylmpl.getWakeUp(PlatformFactorylmpljava:79)
com.baidu.duer.dcs.androidapp.DcsSampleMainActivityinitFramework(DcsSampleMainActivity.java:226)
at
com.baidu.duer.dcs.androidapp.DcsSampleMainActivity.onCreate(DcsSampleMainActivity.java:84)
at android.app.Activity.performCreate(Activityjava:7088)
at android.app.Activity.performCreate(Activityjava:7079)
at android.app.lnstrumentation.callActivityOnCreate(nstrumentation.java:1215)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2768)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2893)
at android .app.ActivityThread.-wrap11(Unknown Source:0)
atandroid.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:171)
at android.app.ActivityThread.main(ActivityThread.java:6649)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Runtimelnit$MethodAndArgsCaller.run(Runtimelnitjava:547)atcom.android.internal.os.Zygotelnit.main(Zygotelnit.java:824)

有人遇到过了吗？

**Comment by 258459885596** [comment]
要libwakeup.so可以找我
